### ISSUE TITLE
Error in compiling \JournalTitle in .bbl

### ISSUE THREAD

**Issue by monodera** [pkgw/yahapj#5]
I'm uploading latex files to arXiv using yahapj-formatted bib style (journal like, etc.).  Since arXiv does not run bibtex, I have to include .bbl file in the .tex file.  When I put it like \input{ms.bbl}, pdflatex stopped with an error like the following.

```
(./ms.bbl
! Undefined control sequence.
<argument> \JournalTitle
                         {\apj }, 765, 140
l.8   765, 140}
```

Is there a way to fix it?

Thanks!

Masato

**Comment by pkgw** [comment]
The top of the .bbl file should [include a line](https://github.com/pkgw/yahapj/blob/master/yahapj.bst#L1553) that provides a default version of the `\JournalTitle` command:

```
\providecommand\JournalTitle[1]{#1}
```

If this line somehow didn't get included, you can always put it in your `.tex` file manually.

**Comment by monodera** [comment]
Thanks for the quick reply.  I saw the definition of `\JournalTitle` in the `.bbl` file.  But for some reason, I had to put the definition of `\JournalTitle` to the preamble of the main `.tex` file manually.  It's working now.
